version: '3.8'

services:
  iob-timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: iob-timescaledb-cluster
    environment:
      POSTGRES_DB: iob_factory_db
      POSTGRES_USER: iob_platform_admin
      POSTGRES_PASSWORD: ${IOB_DATABASE_SECURE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - tsdb_storage_volume:/var/lib/postgresql/data
    networks:
      - iob-industrial-backbone-network

  iob-emqx-broker:
    image: emqx/emqx:5.1.1
    container_name: iob-emqx-backbone
    ports:
      - "1883:1883"
      - "18083:18083"
    networks:
      - iob-industrial-backbone-network

  iob-subscriber-pipeline:
    build:
      context: ./pipeline_engine
      dockerfile: Dockerfile
    container_name: iob-ingestion-subscriber
    environment:
      IOB_DATABASE_URL: "postgresql://iob_platform_admin:${IOB_DATABASE_SECURE_PASSWORD}@iob-timescaledb:5432/iob_factory_db"
      IOB_MQTT_BROKER_URL: "mqtt://iob-emqx-broker:1883"
    depends_on:
      - iob-timescaledb
      - iob-emqx-broker
    networks:
      - iob-industrial-backbone-network

volumes:
  tsdb_storage_volume:
    driver: local

networks:
  iob-industrial-backbone-network:
    driver: bridge
