/* eslint-disable */
/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate_ts_models.py (Phase 4, R-4.1.1)
 * from the backend OpenAPI schema (Pydantic model definitions).
 *
 * Regenerate with:  python scripts/generate_ts_models.py
 */

// Source: Industrial Operating Brain v5.0.0 — generated 2026-07-17T11:28:32Z

/** Alarm acknowledgment request. */
export interface AlarmAcknowledgeRequest {
  /** Acknowledgment notes */
  notes?: null | string;
}

/** Alarm resolution request. */
export interface AlarmResolveRequest {
  /** Resolution notes */
  resolution_notes: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/** POST /api/v1/auth/login body. */
export interface LoginRequest {
  email: string;
  password: string;
}

/** Permission creation request. */
export interface PermissionCreate {
  /** Permission name */
  name: string;
  /** Resource name */
  resource: string;
  /** Action (read/write/delete) */
  action: string;
  description?: null | string;
}

/** Permission response model. */
export interface PermissionResponse {
  /** Permission name */
  name: string;
  /** Resource name */
  resource: string;
  /** Action (read/write/delete) */
  action: string;
  description?: null | string;
  /** Unique permission identifier */
  id: string;
  /** Creation timestamp (UTC ISO 8601 — R-4.4.1) */
  created_at: string;
}

/** POST /api/v1/auth/refresh body. */
export interface RefreshRequest {
  refresh_token: string;
}

/** Role creation request. */
export interface RoleCreate {
  /** Role name */
  name: string;
  description?: null | string;
  /** Assigned permissions */
  permissions?: string[];
}

/** Role response model. */
export interface RoleResponse {
  /** Role name */
  name: string;
  description?: null | string;
  /** Assigned permissions */
  permissions?: string[];
  /** Unique role identifier */
  id: string;
  /** Creation timestamp (UTC ISO 8601 — R-4.4.1) */
  created_at: string;
  /** System role flag */
  is_system?: boolean;
}

/** Role update request. */
export interface RoleUpdate {
  name?: null | string;
  description?: null | string;
  permissions?: null | string[];
}

/** Paginated user list response. */
export interface UserListResponse {
  /** List of users */
  users: app__schemas__users__UserResponse[];
  /** Total count */
  total: number;
  /** Current page */
  page: number;
  /** Items per page */
  page_size: number;
  /** Total pages */
  total_pages: number;
}

/** User update request. */
export interface UserUpdate {
  /** User email */
  email?: null | string;
  full_name?: null | string;
  is_active?: boolean | null;
  roles?: null | string[];
}

export interface ValidationError {
  loc: Array<number | string>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface app__schemas__user__UserCreate {
  /** Unique user authentication identifier email account */
  email: string;
  /** Legal full name designation */
  full_name: string;
  /** Plaintext password matching Stage-5 minimum length specifications */
  password: string;
}

export interface app__schemas__user__UserResponse {
  /** Unique user authentication identifier email account */
  email: string;
  /** Legal full name designation */
  full_name: string;
  /** Unique database surrogate integer key identifier */
  id: number;
  /** Flag indicating if the user profile account status is active */
  is_active?: boolean;
  /** UTC timestamp documenting instance generation time (UTC ISO 8601 — R-4.4.1) */
  created_at?: string;
}

/** User creation request. */
export interface app__schemas__users__UserCreate {
  /** User email */
  email: string;
  /** Full name */
  full_name: string;
  /** Account active status */
  is_active?: boolean;
  /** Assigned roles */
  roles?: string[];
  /** Initial password */
  password: string;
}

/** User response model. */
export interface app__schemas__users__UserResponse {
  /** User email */
  email: string;
  /** Full name */
  full_name: string;
  /** Account active status */
  is_active?: boolean;
  /** Assigned roles */
  roles?: string[];
  /** Unique user identifier */
  id: string;
  /** Account creation timestamp (UTC ISO 8601 — R-4.4.1) */
  created_at: string;
  /** Last update timestamp (UTC ISO 8601 — R-4.4.1) */
  updated_at: string;
  /** Last login timestamp */
  last_login?: null | string;
}
