"""
TypeScript Model Generator — Phase 4 (R-4.1.1)
Industrial Operating Brain (IOB) Platform

Generates TypeScript interfaces directly from the backend's OpenAPI schema
(which FastAPI derives from the Pydantic models) so frontend types can never
silently drift from the backend contract.

Usage:
    python scripts/generate_ts_models.py [output_path]

Default output: frontend/src/types/api-models.generated.ts

Wire this into the frontend build sequence (e.g. a prebuild npm script or
CI step) so every build regenerates the interfaces from the live backend
definitions — this is the automated type-safety gate recommended by the
Phase 4 Engineering Handbook, Section 1, Recommendation R-4.1.1.
"""

from __future__ import annotations

import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict

# Make the project root importable when the script is run from anywhere.
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

os.environ.setdefault("SECRET_KEY", "development-only-secret-key-change-before-deploying")

HEADER = """/* eslint-disable */
/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate_ts_models.py (Phase 4, R-4.1.1)
 * from the backend OpenAPI schema (Pydantic model definitions).
 *
 * Regenerate with:  python scripts/generate_ts_models.py
 */
"""

_TS_PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _sanitize_name(name: str) -> str:
    """Convert an OpenAPI component name into a valid TS identifier."""
    out = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    if out and out[0].isdigit():
        out = "_" + out
    return out


def _ref_name(ref: str) -> str:
    return _sanitize_name(ref.split("/")[-1])


def _ts_type(schema: Dict[str, Any]) -> str:
    """Translate a JSON-schema fragment into a TypeScript type expression."""
    if not schema:
        return "unknown"
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "anyOf" in schema or "oneOf" in schema:
        variants = schema.get("anyOf") or schema.get("oneOf") or []
        parts = sorted({_ts_type(v) for v in variants})
        return " | ".join(parts) if parts else "unknown"
    if "allOf" in schema:
        parts = [_ts_type(v) for v in schema["allOf"]]
        return " & ".join(parts) if parts else "unknown"
    if "enum" in schema:
        return " | ".join(
            f'"{v}"' if isinstance(v, str) else str(v).lower() for v in schema["enum"]
        )

    schema_type = schema.get("type")
    if schema_type == "array":
        item_type = _ts_type(schema.get("items", {}))
        if " " in item_type:
            return f"Array<{item_type}>"
        return f"{item_type}[]"
    if schema_type == "object" or "properties" in schema:
        props = schema.get("properties")
        if not props:
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                return f"Record<string, {_ts_type(additional)}>"
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = []
        for key, val in props.items():
            optional = "" if key in required else "?"
            fields.append(f"  {key}{optional}: {_ts_type(val)};")
        return "{\n" + "\n".join(fields) + "\n}"
    if schema_type in _TS_PRIMITIVES:
        # Preserve ISO 8601 intent in docs; TS type is still string.
        return _TS_PRIMITIVES[schema_type]
    return "unknown"


def _emit_interface(name: str, schema: Dict[str, Any]) -> str:
    description = schema.get("description")
    lines = []
    if description:
        lines.append("/** " + description.replace("*/", "*\\/").strip() + " */")

    if schema.get("enum") or schema.get("type") not in (None, "object"):
        # Enums and aliases become `export type`
        lines.append(f"export type {name} = {_ts_type(schema)};")
        return "\n".join(lines)

    required = set(schema.get("required", []))
    props = schema.get("properties", {})
    lines.append(f"export interface {name} {{")
    for key, val in props.items():
        optional = "" if key in required else "?"
        field_desc = val.get("description")
        fmt = val.get("format")
        doc_parts = []
        if field_desc:
            doc_parts.append(field_desc.strip())
        if fmt == "date-time":
            doc_parts.append("(UTC ISO 8601 — R-4.4.1)")
        if doc_parts:
            lines.append("  /** " + " ".join(doc_parts).replace("*/", "*\\/") + " */")
        lines.append(f"  {key}{optional}: {_ts_type(val)};")
    lines.append("}")
    return "\n".join(lines)


def generate(output_path: str) -> int:
    from app.main import app  # imported lazily so env bootstrap applies first

    openapi = app.openapi()
    components = openapi.get("components", {}).get("schemas", {})

    blocks = [HEADER]
    blocks.append(
        f"// Source: {openapi.get('info', {}).get('title', 'IOB')} "
        f"v{openapi.get('info', {}).get('version', '?')} — generated "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
    )

    for raw_name in sorted(components):
        name = _sanitize_name(raw_name)
        blocks.append(_emit_interface(name, components[raw_name]))
        blocks.append("")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(blocks))

    print(f"[R-4.1.1] Generated {len(components)} TypeScript models -> {output_path}")
    return len(components)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "frontend/src/types/api-models.generated.ts"
    generate(target)
