version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: iob_mqtt_broker
    ports:
      - '1883:1883'
      - '9001:9001'
    restart: unless-stopped
  postgres:
    image: postgres:15-alpine
    container_name: iob_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iob
    ports:
      - '5432:5432'
    restart: unless-stopped
